spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_listener
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

